iiitv/ChefLib

- README.md
> Fixed grammatical error in README

- README.md
> Improved Badges

- 2016/DEC.md
- 2017/APR.md
- 2017/FEB.md
- 2017/JAN.md
- 2017/JUN.md
- 2017/MAR.md
- 2017/MAY.md
> Fixed README HTML tags

- 2017/AUG.md
- 2017/JULY.md
- README.md
> Months Added

- 2017/JULY.md
- README.md
> Removed COOK84

- README.md
> Contibutions Badge Added

- 2017/AUG.md
- 2017/AUG/AUG17/RAINBOWA/RAINBOWA.cpp
> RAINBOWA (AUG17) [CPP] #65

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
> Changed Templates

- 2017/JULY.md
- 2017/JULY/JULY17/CHEFSIGN/CHEFSIGN.py
> Added CHEFSIGN (JULY17) [Python]

- .editorconfig
> Fixed error in .editorconfig

- 2017/JULY.md
- 2017/JULY/JULY17/CALC/CALC.py
> CALC (JULY17) [Python]

- 2017/JULY.md
- 2017/JULY/JULY17/NITIKA/NITIKA.py
> Added NITIKA (JULY17) [Python]

- 2017/AUG.md
- 2017/AUG/AUG17/GCAC/GCAC.cpp
> Added GCAC (AUG17) [CPP]

- 2017/FEB.md
- 2017/FEB/LTIME45/COOMILK/COOMILK.cpp
> Added COOMILK (LTIME45) [C++]

- 2017/AUG.md
- 2017/AUG/COOK85/ELEVSTRS/ELEVSTRS.cpp
> ELEVSTRS (COOK85) [C++]

- 2017/JULY.md
- 2017/JULY/LTIME50/MAXOR.cpp
> MAXOR (LTIME50) [CPP]

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
> Update links in README.md and Templates.

- .codeclimate.yml
> Added .codeclimate.yml

- 2017/JAN.md
> Changed Problem name to NOTINCOM in LTIME44

- 2017/AUG.md
- 2017/AUG/LTIME51/MATPAN/MATPAN.cpp
> MATPAN (LTIME51) [CPP]

- 2017/AUG.md
- 2017/AUG/AUG17/RAINBOWA/RAINBOWA.java
> RAINBOWA (AUG17) [Java]

- 2017/JAN.md
- 2017/JAN/COOK78/LISDIGIT/LISDIGIT.cpp
> LISDIGIT (COOK78) [C++]

- 2017/JUN.md
- 2017/JUNE/COOK83/ADACRA/ADACRA.cpp
> ADACRA (COOK83) [C++]

- CONTRIBUTING.md
> Fixed C/C++ code samples

- 2017/SEPT.md
- README.md
> Added September's README

- 2016/DEC.md
- 2017/APR.md
- 2017/AUG.md
- 2017/FEB.md
- 2017/JAN.md
- 2017/JULY.md
- 2017/JUN.md
- 2017/MAR.md
- 2017/MAY.md
- 2017/SEPT.md
- README.md
> Fixed new issue links in month READMEs

- README.md
> Changed September Lunchtime to LTIME52

- .github/ADD_ME_IN_README.md
- README.md
> added a general add me in readme template

- 2017/SEPT.md
- 2017/SEPT/SEPT17/MINPERM/MINPERM.py
> MINPERM (SEPT17) [Python]

- 2017/SEPT.md
- 2017/SEPT/SEPT17/FILLMTR/FILLMTR.cpp
> FILLMTR (SEPT17) [C++]

- 2017/SEPT.md
- 2017/SEPT/SEPT17/CHEFSUM/CHEFSUM.py
> CHEFSUM (SEPT17) [Python]

- README.md
> Add Codeclimate Badge

- 2017/SEPT.md
- 2017/SEPT/COOK86/LIKECS01/LIKECS01.cpp
> LIKECS01 (COOK86) [C++]

- 2017/FEB.md
- 2017/FEB/FEB17/DISTNUM3/DISTNUM3.cpp
> DISTNUM3 (FEB17) [C++]

- README.md
> Adds Travis CI Build Status badge

- CODE-OF-CONDUCT.md
Hope I did this correct, my 3rd ever PR. Found issue via Hacktoberfest, if not I'd love to know what i need to correct. Thanks for this opportunity.
Fixes #229 
- [] This solution is prepared by me and not copied from anywhere else on the web.
> enhancement Added CODE-OF-CONDUCT.md

- README.md
> fixes #252, fixed grammatical error in README.md
